# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Prueba_CamposV.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QWidget

import PruebasUnitarias.PruebasAuxiliar as Puaux
from Presentacion.Hasse import Hasse


class Ui_Form(QWidget):
    def setupUi(self):
        self.setObjectName("Form")
        self.resize(750, 450)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(self)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 728, 428))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

        self.attachImage()

    def attachImage(self):
        sc = Puaux.crear_sc_prueba()
        hasse = Hasse(sc)
        hasse.paint_edges_for_sim(sc.simplex[1], "blue", True)
        hasse.point_up_edge(sc.simplex[4], sc.simplex[0])
        hasse.point_up_edge(sc.simplex[5], sc.simplex[2])
        hasse.point_up_edge(sc.simplex[6], sc.simplex[3])
        hasse.point_up_edge(sc.simplex[7], sc.simplex[1])
        hasse.plot_hasse()
        path = "../Recursos/Hasse.png"
        pixMap = QtGui.QPixmap(path)
        self.label.setPixmap(pixMap)
        self.scrollArea.setWidgetResizable(True)
        self.label.setAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Form", "Form"))



app = QApplication(sys.argv)

window = Ui_Form()
window.setupUi()
window.show()

app.exec()
