# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TFG_Listar_SC.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(750, 450)
        Form.setStyleSheet("background-color: rgb(27, 27, 27);\n"
"color: rgb(255, 255, 255);")
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setHorizontalSpacing(20)
        self.gridLayout.setObjectName("gridLayout")
        self.toolButton_load = QtWidgets.QToolButton(Form)
        self.toolButton_load.setMinimumSize(QtCore.QSize(40, 40))
        self.toolButton_load.setStyleSheet("QToolButton{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(71, 71, 71);\n"
"}\n"
"\n"
"QToolButton:hover{\n"
"    background-color: rgb(100, 100, 100);\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/load.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_load.setIcon(icon)
        self.toolButton_load.setIconSize(QtCore.QSize(32, 32))
        self.toolButton_load.setObjectName("toolButton_load")
        self.gridLayout.addWidget(self.toolButton_load, 0, 0, 1, 1)
        self.toolButton_remove = QtWidgets.QToolButton(Form)
        self.toolButton_remove.setMinimumSize(QtCore.QSize(40, 40))
        self.toolButton_remove.setStyleSheet("QToolButton{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(71, 71, 71);\n"
"}\n"
"\n"
"QToolButton:hover{\n"
"    background-color: rgb(100, 100, 100);\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/remove.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_remove.setIcon(icon1)
        self.toolButton_remove.setIconSize(QtCore.QSize(32, 32))
        self.toolButton_remove.setObjectName("toolButton_remove")
        self.gridLayout.addWidget(self.toolButton_remove, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.tableSC = QtWidgets.QTableWidget(Form)
        self.tableSC.setMinimumSize(QtCore.QSize(725, 300))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tableSC.setFont(font)
        self.tableSC.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(177, 177, 177);")
        self.tableSC.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableSC.setAlternatingRowColors(True)
        self.tableSC.setObjectName("tableSC")
        self.tableSC.setColumnCount(6)
        self.tableSC.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 255, 255))
        self.tableSC.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableSC.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableSC.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableSC.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableSC.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableSC.setHorizontalHeaderItem(5, item)
        self.tableSC.horizontalHeader().setCascadingSectionResizes(False)
        self.tableSC.horizontalHeader().setDefaultSectionSize(100)
        self.tableSC.verticalHeader().setCascadingSectionResizes(False)
        self.gridLayout.addWidget(self.tableSC, 1, 0, 1, 3)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.toolButton_load.setText(_translate("Form", "..."))
        self.toolButton_remove.setText(_translate("Form", "..."))
        item = self.tableSC.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Nombre"))
        item = self.tableSC.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Ω"))
        item = self.tableSC.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Dimensión"))
        item = self.tableSC.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Característica de Euler"))
        item = self.tableSC.horizontalHeaderItem(4)
        item.setText(_translate("Form", "C-Vector"))
        item = self.tableSC.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Nº Símplices"))
import resources_rc
